#################################     IRC     #################################
[irc]

  [irc.dtek]
  Server = "localhost:6667"
  Nick = "Discord"
  SkipTLSVerify = true

  [irc.tgbot]
  Server="irc.dtek.se:6697"
  RemoteNickFormat="<tg-{NICK}> "
  UseTLS=true
  SkipTLSVerify=true
  Nick="telegrambot"
  Password=MATTERBRIDGE_IRC_TGBOT_PASSWORD
  Charset="utf-8"

############################     Dtek Telegram     ############################
[telegram]

  [telegram.dtekirc]
  Token=MATTERBRIDGE_TELEGRAM_DTEKIRC_TOKEN
  RemoteNickFormat="&lt;{NICK}&gt; "
  MessageFormat="HTMLNick"

###############################     Discord     ###############################
[discord]

  [discord.clipboard]
  Token = DISCORD_TOKEN
  Server = "Datateknologsektionen, Chalmers Studentkår"

###############################     General     ###############################
[general]
RemoteNickFormat="<{NICK}> "

############################     #dtek Gateway     ############################
[[gateway]]
  name = "dtek"
  enable = true

  [[gateway.inout]]
  account ="irc.dtek"
  channel = "#dtek"

  [[gateway.inout]]
  account = "discord.clipboard"
  channel = "irc"

  [[gateway.inout]]
  account="telegram.dtekirc"
  channel="-292431925"

############################     DHack Gateway     ############################
[[gateway]]
name="dhack"
enable=true

    [[gateway.inout]]
    account="irc.tgbot"
    channel="#dhack"

    [[gateway.inout]]
    account="telegram.dtekirc"
    channel="-314089083"

##########################     Dtek Spam Gateway     ##########################
[[gateway]]
name="tg_dtek_spam"
enable=true

    [[gateway.inout]]
    account="irc.tgbot"
    channel="#dtek-spam"

    [[gateway.inout]]
    account="telegram.dtekirc"
    channel="-1001393278925"

